name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby Test
    env:
      BUNDLE_WITHOUT: deployment

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache:
            true # Runs bundle install and caches gems. See the ruby_test.yml
            # example if you need more control over bundler.
      - name: Run tests
        run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    name: Ruby lint and format
    env:
      BUNDLE_WITHOUT: deployment

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache:
            true # Runs bundle install and caches gems. See the ruby_test.yml
            # example if you need more control over bundler.
      - name: Run prettier
        run: bundle exec rbprettier --check .
      - name: Run rubocop
        run: bundle exec rubocop
